"""Scapy layers and CRC helpers for the project's RoCE-v2 wire format.

Ethernet, ARP, IPv4, and UDP are intentionally provided by Scapy. This module
only describes the InfiniBand headers used by the RTL, the project-specific
connection-setup payload, and the real/RTL ICRC variants.
"""

import binascii
import struct
from enum import IntEnum

from scapy.fields import (BitField, ByteEnumField, ByteField, IntField,
                          LEIntField, LEShortField, LongField,
                          StrFixedLenField, ThreeBytesField, XByteField,
                          XShortField)
from scapy.layers.inet import IP, UDP
from scapy.layers.l2 import Ether
from scapy.packet import Packet, Raw, bind_layers

__all__ = (
    "AETH",
    "BTH",
    "BthOpcode",
    "ICRC_SIZE",
    "RDMAConnectionSetup",
    "RETH",
    "ROCE_PORT",
    "compute_icrc",
    "compute_rtl_icrc",
    "finalize_roce",
    "icrc_matches",
)

ROCE_PORT = 4791
ICRC_SIZE = 4


class BthOpcode(IntEnum):
    RC_RDMA_WRITE_ONLY = 0x0A
    RC_RDMA_READ_REQUEST = 0x0C
    RC_RDMA_READ_RESPONSE_ONLY = 0x10
    RC_ACKNOWLEDGE = 0x11


_BTH_OPCODES = {int(opcode): opcode.name for opcode in BthOpcode}


class BTH(Packet):
    """InfiniBand Base Transport Header used by the RC subset."""

    name = "BTH"
    fields_desc = [
        ByteEnumField("opcode", int(BthOpcode.RC_RDMA_WRITE_ONLY),
                      _BTH_OPCODES),
        BitField("solicited", 0, 1),
        BitField("migration", 0, 1),
        BitField("pad_count", 0, 2),
        BitField("version", 0, 4),
        XShortField("partition", 0xFFFF),
        XByteField("reserved", 0),
        ThreeBytesField("dest_qp", 2),
        BitField("ack_req", 0, 1),
        BitField("reserved7", 0, 7),
        ThreeBytesField("psn", 0),
    ]

    def __init__(self, *args, **kwargs):
        for name in ("dest_qp", "psn"):
            value = kwargs.get(name)
            if value is not None and not 0 <= value < (1 << 24):
                raise ValueError(f"{name} out of range: {value}")
        pad_count = kwargs.get("pad_count")
        if pad_count is not None and not 0 <= pad_count <= 3:
            raise ValueError(f"pad_count out of range: {pad_count}")
        super().__init__(*args, **kwargs)

    def guess_payload_class(self, payload):
        if self.opcode in (BthOpcode.RC_RDMA_WRITE_ONLY,
                           BthOpcode.RC_RDMA_READ_REQUEST):
            return RETH
        if self.opcode in (BthOpcode.RC_RDMA_READ_RESPONSE_ONLY,
                           BthOpcode.RC_ACKNOWLEDGE):
            return AETH
        return super().guess_payload_class(payload)


class RETH(Packet):
    """RDMA Extended Transport Header."""

    name = "RETH"
    fields_desc = [
        LongField("vaddr", 0),
        IntField("r_key", 0),
        IntField("dmalen", 0),
    ]


class AETH(Packet):
    """ACK Extended Transport Header."""

    name = "AETH"
    fields_desc = [
        ByteField("syndrome", 0),
        ThreeBytesField("msn", 0),
    ]


class RDMAConnectionSetup(Packet):
    """Payload consumed by the test RDMA connection server."""

    name = "RDMAConnectionSetup"
    fields_desc = [
        LEIntField("local_qpn", 2),
        LEIntField("remote_qpn", 2),
        StrFixedLenField("remote_ip", b"\x00" * 16, length=16),
        LEShortField("remote_port", 8000),
        LEIntField("initial_rx_psn", 0),
    ]


bind_layers(UDP, BTH, dport=ROCE_PORT)
bind_layers(UDP, BTH, sport=ROCE_PORT)
bind_layers(UDP, RDMAConnectionSetup, dport=8000)


def compute_icrc(ip_and_payload):
    """Return the standard RoCE-v2 invariant CRC in wire byte order."""
    if len(ip_and_payload) < 20 + 8 + 12:
        raise ValueError("packet too short for RoCE-v2 ICRC")
    ihl = (ip_and_payload[0] & 0x0F) * 4
    if ihl < 20 or len(ip_and_payload) < ihl + 8 + 12:
        raise ValueError("invalid IPv4 header for RoCE-v2 ICRC")

    invariant = bytearray(ip_and_payload)
    invariant[1] = 0xFF
    invariant[8] = 0xFF
    invariant[10:12] = b"\xff\xff"
    invariant[ihl + 6:ihl + 8] = b"\xff\xff"
    invariant[ihl + 8 + 4] = 0xFF
    crc = binascii.crc32(b"\xff" * 8 + invariant) & 0xFFFFFFFF
    return struct.pack("<I", crc)


def compute_rtl_icrc(ip_and_payload):
    """Return the plain CRC-32 currently generated by ``CrcInsert``."""
    return struct.pack("<I", binascii.crc32(ip_and_payload) & 0xFFFFFFFF)


def _serialized_with_placeholder(packet, mode):
    packet = packet.copy()
    if (Ether not in packet or IP not in packet or UDP not in packet
            or BTH not in packet):
        raise ValueError("RoCE packet must contain Ether, IP, UDP, and BTH layers")
    packet[IP].len = None
    packet[IP].chksum = None
    packet[UDP].len = None
    packet[UDP].chksum = 0 if mode == "rtl" else None
    return bytes(packet / Raw(b"\x00" * ICRC_SIZE))


def finalize_roce(packet, mode="roce"):
    """Serialize a Scapy RoCE packet and append its real or RTL ICRC.

    The packet must end after its BTH extended header, payload, and BTH padding;
    it must not already contain an ICRC. Standard IPv4 and UDP lengths and
    checksums are recalculated by Scapy. RTL mode deliberately keeps the UDP
    checksum at zero to match the current transmitter.
    """
    if mode not in ("roce", "rtl"):
        raise ValueError(f"unknown ICRC mode: {mode!r}")

    provisional = _serialized_with_placeholder(packet, mode)
    crc_input = provisional[14:-ICRC_SIZE]
    icrc = (compute_icrc(crc_input) if mode == "roce"
            else compute_rtl_icrc(crc_input))

    packet = packet.copy()
    packet[IP].len = None
    packet[IP].chksum = None
    packet[UDP].len = None
    packet[UDP].chksum = 0 if mode == "rtl" else None
    return bytes(packet / Raw(icrc))


def icrc_matches(frame, mode="roce"):
    """Check the trailing ICRC of an Ethernet/IPv4 RoCE frame."""
    frame = bytes(frame)
    if len(frame) < 14 + 20 + 8 + 12 + ICRC_SIZE:
        return False
    crc_input = frame[14:-ICRC_SIZE]
    expected = (compute_icrc(crc_input) if mode == "roce"
                else compute_rtl_icrc(crc_input))
    return frame[-ICRC_SIZE:] == expected
